version: '3'

services:
  go:
    build: .
    container_name: gobank
    # environment:
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: postgres
    #   POSTGRES_USER: postgres
    tty: true
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - pgdb
    networks:
      - learning

  pgdb:
    image: postgres
    restart: always
    container_name: pgdb
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - learning
  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  learning:
    driver: bridge